version: '2.7'

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: covid
    restart: on-failure
    ports:
        - "5432:5432"
  superset:
    build: ./docker/superset
    ports:
      - "8088:8088"
  neo4j:
    image: neo4j:4.1.1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/root
